version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672"  # Management UI
      - "5673:5672"    # AMQP port (exposed on a different host port to avoid conflict with proxy)
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  amqp-router:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: amqp-router
    ports:
      - "5672:5672"  # AMQP router port
    depends_on:
      rabbitmq:
        condition: service_healthy
    command:
      - "--listen"
      - "0.0.0.0:5672"

volumes:
  rabbitmq_data:
    driver: local